### ISSUE TITLE
weed mount lost data

### ISSUE THREAD

**Issue by rensongqi** [seaweedfs/seaweedfs#6257]
Hi, I found an error, client exec `weed mount` command after a few days of data is not synchronized, is there something wrong with the `weed mount` command parameter?

weed mount:
`weed mount -filer=172.16.90.172:8888,172.16.90.173:8888,172.16.90.174:8888 -filer.path=/buckets/aistudiodata/dcenter/DriveData -dir=/disk1/AIStudiodata/dcenter/DriveData -cacheDir=/mnt -readOnly -nonempty`

client1 files:
![image](https://github.com/user-attachments/assets/a18622eb-c044-4138-8503-36b3080c8b44)

client2 files:
![image](https://github.com/user-attachments/assets/7a22e57c-f4e8-4465-972a-ed796f099428)

The client1 lost three days of data and recovered after re-mounting `weed mount`
![20241119-105729](https://github.com/user-attachments/assets/287ba5c5-f884-48e0-ab8a-f5941cb73cac)

client1 log(no error):
![image](https://github.com/user-attachments/assets/bbebab19-b4d3-4875-a60b-e00e68de4d76)

Version: `version 8000GB 3.75 117c3aebda7906433b4b83419af3acbc47f09f4d linux amd64`

OS: `ubuntu22.04`

docker-compose.yml
```yaml
version: '3.8'
services:
  seaweedfs-master:
    image: docker.io/chrislusf/seaweedfs:3.75_large_disk_full
    container_name: seaweedfs-master
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /data/seaweedfs/config:/etc/seaweedfs:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      master 
      -mdir=/weed/metadata
      -peers=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=9333
      -metricsPort=9999
      -volumeSizeLimitMB=1000000
      -maxParallelVacuumPerServer=8
      -volumePreallocate

  seaweedfs-volume:
    image: docker.io/chrislusf/seaweedfs:3.75_large_disk_full
    deploy:
      resources:
        limits:
          memory: 96G
    container_name: seaweedfs-volume
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /disk/local_disk1:/disk/local_disk1:rw
      - /disk/local_disk2:/disk/local_disk2:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      volume 
      -mserver=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=8080
      -dir=/disk/local_disk1,/disk/local_disk2
      -dir.idx=/weed/metadata
      -max=0,0
      -index=leveldbMedium
      -minFreeSpace=1
      -metricsPort=9998
      -readBufferSizeMB=64
      -dataCenter=SHJD
      -disk=hdd
      -rack=B07

  seaweedfs-filer:
    image: docker.io/chrislusf/seaweedfs:3.75_large_disk_full
    container_name: seaweedfs-filer
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /data/seaweedfs/config:/etc/seaweedfs:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      filer
      -master=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=8888
      -port.grpc=18888
      -port.readonly=28888
      -maxMB=64
      -ui.deleteDir=false
      -metricsPort=9997
```

**Comment by chrislusf** [comment]
try using latest version.

this should have been fixed in https://github.com/seaweedfs/seaweedfs/pull/6183

**Comment by rensongqi** [comment]
> try using latest version.
> 
> this should have been fixed in #6183

Thank you. I'll try it.

**Comment by Sagar9921** [comment]
@rensongqi have you tried it?

**Comment by rensongqi** [comment]
> @rensongqi have you tried it?

Try, but still have the same problem, in the Filer web data is available, but the client mount data is still inconsistent, need to restart client weed mount

**Comment by zemul** [comment]
@chrislusf get file metadata from the filer is more reliable than event push notifications and is more conducive to scalability.
